import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import CustomFont from "next/font/local";
const cfont = CustomFont({
  src: "../public/e-Ukraine-Regular.otf",
  variable: "--font-cfont",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cfont.variable}`}>
      <body className=" font-cfont bg-black text-white">
        {children}
        <Footer />
      </body>
    </html>
  );
}
